/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author Rodrigo Desktop
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uJPanelImagem1 = new componentes.UJPanelImagem();
        MenuBarra = new javax.swing.JMenuBar();
        MArquivos = new javax.swing.JMenu();
        MSair = new javax.swing.JMenuItem();
        MCadastros = new javax.swing.JMenu();
        MClientes = new javax.swing.JMenuItem();
        MFilmes = new javax.swing.JMenuItem();
        MUsuarios = new javax.swing.JMenuItem();
        MVendas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        uJPanelImagem1.setImagem(new java.io.File("C:\\Users\\rodri\\OneDrive\\Área de Trabalho\\Video-1024x842.jpg"));

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1076, Short.MAX_VALUE)
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        MenuBarra.setBackground(new java.awt.Color(51, 0, 255));

        MArquivos.setText("Sair");
        MArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MArquivosActionPerformed(evt);
            }
        });

        MSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        MSair.setText("Sair");
        MSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSairActionPerformed(evt);
            }
        });
        MArquivos.add(MSair);

        MenuBarra.add(MArquivos);

        MCadastros.setBackground(new java.awt.Color(51, 51, 255));
        MCadastros.setText("Cadastros");

        MClientes.setText("Clientes");
        MClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MClientesActionPerformed(evt);
            }
        });
        MCadastros.add(MClientes);

        MFilmes.setText("Filmes");
        MFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFilmesActionPerformed(evt);
            }
        });
        MCadastros.add(MFilmes);

        MUsuarios.setText("Usuários");
        MUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MUsuariosActionPerformed(evt);
            }
        });
        MCadastros.add(MUsuarios);

        MenuBarra.add(MCadastros);

        MVendas.setText("Locacoes");

        jMenuItem1.setText("Reserva");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MVendas.add(jMenuItem1);

        MenuBarra.add(MVendas);

        setJMenuBar(MenuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MArquivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MArquivosActionPerformed

    private void MSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MSairActionPerformed

    private void MClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MClientesActionPerformed
        // TODO add your handling code here:
        new ViewCliente().setVisible(true);
    }//GEN-LAST:event_MClientesActionPerformed

    private void MFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFilmesActionPerformed
        // TODO add your handling code here:
        new ViewCadFilme().setVisible(true);
    }//GEN-LAST:event_MFilmesActionPerformed

    private void MUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MUsuariosActionPerformed
        // TODO add your handling code here:
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_MUsuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new ViewReserva().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MArquivos;
    private javax.swing.JMenu MCadastros;
    private javax.swing.JMenuItem MClientes;
    private javax.swing.JMenuItem MFilmes;
    private javax.swing.JMenuItem MSair;
    private javax.swing.JMenuItem MUsuarios;
    private javax.swing.JMenu MVendas;
    private javax.swing.JMenuBar MenuBarra;
    private javax.swing.JMenuItem jMenuItem1;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables
}
