/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelCliente;

/**
 *
 * @author Rodrigo Desktop
 */
public class ViewCliente extends javax.swing.JFrame {

    controller.ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelClientes = new ArrayList<>();
    String SalvarAlterar;
    
    /**
     * Creates new form save
     */
    public ViewCliente() {
        initComponents();
        carregarCliente();
        setLocationRelativeTo(null);
        habilitarDesabilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Cliente = new javax.swing.JTable();
        CNome = new javax.swing.JTextField();
        LCEP = new javax.swing.JLabel();
        ButExcluir = new javax.swing.JButton();
        ButAlterar = new javax.swing.JButton();
        ButSalvar = new javax.swing.JButton();
        CCep = new javax.swing.JFormattedTextField();
        LLogradouro = new javax.swing.JLabel();
        ButCancelar = new javax.swing.JButton();
        CEndereço = new javax.swing.JTextField();
        CTelefone = new javax.swing.JFormattedTextField();
        LCelular = new javax.swing.JLabel();
        LCidade = new javax.swing.JLabel();
        ButNovo = new javax.swing.JButton();
        CCidade = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Cadast_Client = new javax.swing.JLabel();
        LBairro = new javax.swing.JLabel();
        Cbairro = new javax.swing.JTextField();
        LIdentificador = new javax.swing.JLabel();
        LUF = new javax.swing.JLabel();
        CIndentificador = new javax.swing.JTextField();
        Caixa_Estados_UF = new javax.swing.JComboBox<>();
        LNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CCpf = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cidade", "Telefone", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_Cliente);
        if (tbl_Cliente.getColumnModel().getColumnCount() > 0) {
            tbl_Cliente.getColumnModel().getColumn(0).setMinWidth(70);
            tbl_Cliente.getColumnModel().getColumn(0).setPreferredWidth(70);
            tbl_Cliente.getColumnModel().getColumn(0).setMaxWidth(70);
            tbl_Cliente.getColumnModel().getColumn(1).setMinWidth(280);
            tbl_Cliente.getColumnModel().getColumn(1).setPreferredWidth(280);
            tbl_Cliente.getColumnModel().getColumn(1).setMaxWidth(280);
        }

        CNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNomeActionPerformed(evt);
            }
        });

        LCEP.setText("CEP");

        ButExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/black_delete.png"))); // NOI18N
        ButExcluir.setText("Excluir");
        ButExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExcluirActionPerformed(evt);
            }
        });

        ButAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/document_edit.gif"))); // NOI18N
        ButAlterar.setText("Alterar");
        ButAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAlterarActionPerformed(evt);
            }
        });

        ButSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save.png"))); // NOI18N
        ButSalvar.setText("Salvar");
        ButSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSalvarActionPerformed(evt);
            }
        });

        try {
            CCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        LLogradouro.setText("Endereço");

        ButCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/symbol_multiplication.gif"))); // NOI18N
        ButCancelar.setText("Cancelar");
        ButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelarActionPerformed(evt);
            }
        });

        try {
            CTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        LCelular.setText("Celular ");

        LCidade.setText("Cidade");

        ButNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Netvibes_16x16.png"))); // NOI18N
        ButNovo.setText("Novo");
        ButNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButNovoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        Cadast_Client.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 24)); // NOI18N
        Cadast_Client.setForeground(new java.awt.Color(255, 255, 255));
        Cadast_Client.setText("Cadastro de cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cadast_Client)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(Cadast_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        LBairro.setText("Bairro");

        LIdentificador.setText("Identificador");

        LUF.setText("UF");

        CIndentificador.setEnabled(false);

        Caixa_Estados_UF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE ", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        LNome.setText("Nome");

        jLabel1.setText("Cpf");

        try {
            CCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LIdentificador)
                        .addGap(87, 745, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LCEP)
                                    .addComponent(LLogradouro)
                                    .addComponent(jLabel1))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CIndentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(LNome)
                                        .addGap(25, 25, 25)
                                        .addComponent(CNome, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LCelular)
                                                .addGap(18, 18, 18)
                                                .addComponent(CTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(CEndereço)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(CCep, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(LCidade)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(CCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LBairro)
                                                    .addComponent(LUF))))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Cbairro)
                                            .addComponent(Caixa_Estados_UF, 0, 145, Short.MAX_VALUE)))))
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ButCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButSalvar)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LIdentificador)
                        .addComponent(CIndentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LNome))
                    .addComponent(CNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCEP)
                    .addComponent(LCidade)
                    .addComponent(CCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LUF)
                    .addComponent(Caixa_Estados_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LLogradouro)
                    .addComponent(CEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBairro)
                    .addComponent(Cbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCelular)
                    .addComponent(CTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(CCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButNovo)
                    .addComponent(ButSalvar)
                    .addComponent(ButCancelar)
                    .addComponent(ButAlterar)
                    .addComponent(ButExcluir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNomeActionPerformed

    private void ButExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExcluirActionPerformed
        // TODO add your handling code here:
        // Exclui um produto do banco de dados
        int linha = tbl_Cliente.getSelectedRow();
        int idCliente = (int) tbl_Cliente.getValueAt(linha, 0);

        if(controllerCliente.excluirClienteController(idCliente)){
            JOptionPane.showMessageDialog(this, "Cliente Excluído com Sucesso!","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
            this.carregarCliente();
        }else
        JOptionPane.showMessageDialog(this, "Erro ao Excluir o Cliente","ERRO",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ButExcluirActionPerformed

    private void ButAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAlterarActionPerformed
        // TODO add your handling code here:
        int linha = this.tbl_Cliente.getSelectedRow();
        try {
            int idCliente = (int) this.tbl_Cliente.getValueAt(linha, 0);
            SalvarAlterar = "alterar";
            // Recupera os dados do banco
            modelCliente = controllerCliente.getClienteController(idCliente);
            // Jogar na interface
            this.CIndentificador.setText(String.valueOf(modelCliente.getIdCliente()));
            this.CNome.setText(modelCliente.getCliNome());
            this.CEndereço.setText(modelCliente.getCliEndereco());
            this.Cbairro.setText(modelCliente.getCliBairro());
            this.CCidade.setText(modelCliente.getCliCidade());
            this.Caixa_Estados_UF.setSelectedItem(modelCliente.getCliUf());
            this.CCep.setText(modelCliente.getCliCep());
            this.CTelefone.setText(modelCliente.getCliCelular());
            this.CCpf.setText(modelCliente.getCliCpf());
            habilitarDesabilitarCampos(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado!","Aviso",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButAlterarActionPerformed

    private void ButSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSalvarActionPerformed
        // TODO add your handling code here:
        try {
            modelCliente.setIdCliente(Integer.parseInt(this.CIndentificador.getText()));
        } catch (NumberFormatException e) {
        }
        modelCliente.setCliNome(this.CNome.getText());
        modelCliente.setCliEndereco(this.CEndereço.getText());
        modelCliente.setCliBairro(this.Cbairro.getText());
        modelCliente.setCliCidade(this.CCidade.getText());
        modelCliente.setCliUf(this.Caixa_Estados_UF.getSelectedItem().toString());
        modelCliente.setCliCep(this.CCep.getText());
        modelCliente.setCliCelular(this.CTelefone.getText());
        modelCliente.setCliCpf(this.CCpf.getText());
        if(SalvarAlterar.equals("salvar")){
            if (controllerCliente.salvarClienteController(modelCliente) > 0){
                JOptionPane.showMessageDialog(this, "Cadastro Realizado com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                carregarCliente();
                habilitarDesabilitarCampos(false);
                LimparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Cadastrar!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            if (controllerCliente.atualizarClienteController(modelCliente)){
                JOptionPane.showMessageDialog(this, "Cadastro Alterado com sucessso com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                carregarCliente();
                habilitarDesabilitarCampos(false);
                LimparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Alterar!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ButSalvarActionPerformed

    private void ButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelarActionPerformed
        // TODO add your handling code here:
        LimparCampos();
        habilitarDesabilitarCampos(false);
    }//GEN-LAST:event_ButCancelarActionPerformed

    private void ButNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButNovoActionPerformed
        // TODO add your handling code here:
        SalvarAlterar = "salvar";
        habilitarDesabilitarCampos(true);
    }//GEN-LAST:event_ButNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAlterar;
    private javax.swing.JButton ButCancelar;
    private javax.swing.JButton ButExcluir;
    private javax.swing.JButton ButNovo;
    private javax.swing.JButton ButSalvar;
    private javax.swing.JFormattedTextField CCep;
    private javax.swing.JTextField CCidade;
    private javax.swing.JFormattedTextField CCpf;
    private javax.swing.JTextField CEndereço;
    private javax.swing.JTextField CIndentificador;
    private javax.swing.JTextField CNome;
    private javax.swing.JFormattedTextField CTelefone;
    private javax.swing.JLabel Cadast_Client;
    private javax.swing.JComboBox<String> Caixa_Estados_UF;
    private javax.swing.JTextField Cbairro;
    private javax.swing.JLabel LBairro;
    private javax.swing.JLabel LCEP;
    private javax.swing.JLabel LCelular;
    private javax.swing.JLabel LCidade;
    private javax.swing.JLabel LIdentificador;
    private javax.swing.JLabel LLogradouro;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_Cliente;
    // End of variables declaration//GEN-END:variables

    private void carregarCliente() {
        listaModelClientes = controllerCliente.getListaClienteController();
        DefaultTableModel modelo = (DefaultTableModel) tbl_Cliente.getModel();
        modelo.setNumRows(0);
        int cont = listaModelClientes.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
            listaModelClientes.get(i).getIdCliente(),
            listaModelClientes.get(i).getCliNome(),
            listaModelClientes.get(i).getCliCidade(),
            listaModelClientes.get(i).getCliCelular(),
            listaModelClientes.get(i).getCliCpf()
            });
        }
    }

    private void habilitarDesabilitarCampos(boolean condicao) {
        CNome.setEnabled(condicao);
        CEndereço.setEnabled(condicao);
        Cbairro.setEnabled(condicao);
        CCidade.setEnabled(condicao);
        Caixa_Estados_UF.setEnabled(condicao);
        CCep.setEnabled(condicao);
        CTelefone.setEnabled(condicao);
        CCpf.setEnabled(condicao);
        ButSalvar.setEnabled(condicao);
    }

    private void LimparCampos() {
        CNome.setText("");
        CEndereço.setText("");
        Cbairro.setText("");
        CCidade.setText("");
        CCep.setText("");
        CTelefone.setText("");
        CCpf.setText("");
    }
}
