/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import controller.ControllerFilme;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.ModelCliente;
import model.ModelFilme;

/**
 *
 * @author Rodrigo Desktop
 */
public class ViewReserva extends javax.swing.JFrame {

    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelClientes = new ArrayList<>();
    ControllerFilme controllerFilme = new ControllerFilme();
    ModelFilme modelFilme = new ModelFilme();
    ArrayList<ModelFilme> listaModelFilme = new ArrayList<>();

    /**
     * Creates new form ViewVendas
     */
    public ViewReserva() {
        initComponents();
        listarClientes();
        listarProdutos();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Paineis = new javax.swing.JTabbedPane();
        PainelCadastro = new javax.swing.JPanel();
        ButCancelar1 = new javax.swing.JButton();
        ButNovo1 = new javax.swing.JButton();
        ButSalvar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_cadastro = new javax.swing.JTable();
        CCodFilm = new javax.swing.JTextField();
        CBXNomeFilme = new componentes.UJComboBox();
        ButAdicionar = new javax.swing.JButton();
        CNumVenda = new javax.swing.JTextField();
        CBXNomeCliente = new componentes.UJComboBox();
        CCodCliente = new javax.swing.JTextField();
        LCodProd = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LCodCliente = new javax.swing.JLabel();
        LNomeCliente = new javax.swing.JLabel();
        LNumVenda = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        PainelConsulta = new javax.swing.JPanel();
        CPesquisaConsulta = new javax.swing.JTextField();
        LPesquisaConsulta = new javax.swing.JLabel();
        ButPesquisaConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_consulta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        ButCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/symbol_multiplication.gif"))); // NOI18N
        ButCancelar1.setText("Cancelar");
        ButCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelar1ActionPerformed(evt);
            }
        });

        ButNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Netvibes_16x16.png"))); // NOI18N
        ButNovo1.setText("Novo");
        ButNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButNovo1ActionPerformed(evt);
            }
        });

        ButSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save.png"))); // NOI18N
        ButSalvar1.setText("Salvar");
        ButSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSalvar1ActionPerformed(evt);
            }
        });

        tbl_cadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Produto", "Nome do Produto", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_cadastro);
        if (tbl_cadastro.getColumnModel().getColumnCount() > 0) {
            tbl_cadastro.getColumnModel().getColumn(1).setMinWidth(300);
            tbl_cadastro.getColumnModel().getColumn(1).setPreferredWidth(300);
            tbl_cadastro.getColumnModel().getColumn(1).setMaxWidth(300);
        }

        CCodFilm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CCodFilmFocusLost(evt);
            }
        });

        CBXNomeFilme.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                CBXNomeFilmePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        CBXNomeFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBXNomeFilmeActionPerformed(evt);
            }
        });

        ButAdicionar.setText("Adicionar");
        ButAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAdicionarActionPerformed(evt);
            }
        });

        CBXNomeCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                CBXNomeClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        CBXNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBXNomeClienteActionPerformed(evt);
            }
        });

        CCodCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CCodClienteFocusLost(evt);
            }
        });

        LCodProd.setText("Cód. Filme");

        jLabel7.setText("Nome do Filme");

        LCodCliente.setText("Cód. Cliente");

        LNomeCliente.setText("Nome do Cliente");

        LNumVenda.setText("Nº da Reserva");

        jLabel1.setText("Valor Total");

        javax.swing.GroupLayout PainelCadastroLayout = new javax.swing.GroupLayout(PainelCadastro);
        PainelCadastro.setLayout(PainelCadastroLayout);
        PainelCadastroLayout.setHorizontalGroup(
            PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(PainelCadastroLayout.createSequentialGroup()
                        .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LCodCliente))
                        .addGap(18, 18, 18)
                        .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LNomeCliente)
                            .addComponent(CBXNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelCadastroLayout.createSequentialGroup()
                                .addComponent(LNumVenda)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(CNumVenda)))
                    .addGroup(PainelCadastroLayout.createSequentialGroup()
                        .addComponent(ButCancelar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButNovo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButSalvar1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelCadastroLayout.createSequentialGroup()
                        .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CCodFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LCodProd))
                        .addGap(18, 18, 18)
                        .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PainelCadastroLayout.createSequentialGroup()
                                .addComponent(CBXNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        PainelCadastroLayout.setVerticalGroup(
            PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCodCliente)
                    .addComponent(LNomeCliente)
                    .addComponent(LNumVenda))
                .addGap(11, 11, 11)
                .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBXNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CNumVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCodProd)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CCodFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBXNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButAdicionar))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButCancelar1)
                    .addComponent(ButNovo1)
                    .addComponent(ButSalvar1))
                .addContainerGap())
        );

        Paineis.addTab("Cadastro", PainelCadastro);

        LPesquisaConsulta.setText("Pesquisa");

        ButPesquisaConsulta.setText("Pesquisa");

        tbl_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome do Cliente", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_consulta);
        if (tbl_consulta.getColumnModel().getColumnCount() > 0) {
            tbl_consulta.getColumnModel().getColumn(0).setMinWidth(100);
            tbl_consulta.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbl_consulta.getColumnModel().getColumn(0).setMaxWidth(100);
            tbl_consulta.getColumnModel().getColumn(1).setMinWidth(430);
            tbl_consulta.getColumnModel().getColumn(1).setPreferredWidth(430);
            tbl_consulta.getColumnModel().getColumn(1).setMaxWidth(430);
        }

        javax.swing.GroupLayout PainelConsultaLayout = new javax.swing.GroupLayout(PainelConsulta);
        PainelConsulta.setLayout(PainelConsultaLayout);
        PainelConsultaLayout.setHorizontalGroup(
            PainelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelConsultaLayout.createSequentialGroup()
                        .addComponent(CPesquisaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButPesquisaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .addGroup(PainelConsultaLayout.createSequentialGroup()
                        .addComponent(LPesquisaConsulta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        PainelConsultaLayout.setVerticalGroup(
            PainelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConsultaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LPesquisaConsulta)
                .addGap(10, 10, 10)
                .addGroup(PainelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPesquisaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButPesquisaConsulta))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        Paineis.addTab("Consultar", PainelConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Paineis)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Paineis)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButCancelar1ActionPerformed

    private void ButNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButNovo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButNovo1ActionPerformed

    private void ButSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSalvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButSalvar1ActionPerformed

    private void CBXNomeFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBXNomeFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBXNomeFilmeActionPerformed

    private void CBXNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBXNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBXNomeClienteActionPerformed

    private void CCodClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CCodClienteFocusLost
        // TODO add your handling code here:
        modelCliente = controllerCliente.getClienteController(Integer.parseInt(CCodCliente.getText()));
        CBXNomeCliente.setSelectedItem(modelCliente.getCliNome());
    }//GEN-LAST:event_CCodClienteFocusLost

    private void CBXNomeClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_CBXNomeClientePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (CBXNomeCliente.isVisible()) {
            CCodCliente.setText(String.valueOf(modelCliente.getIdCliente()));
        }
    }//GEN-LAST:event_CBXNomeClientePopupMenuWillBecomeInvisible

    private void CBXNomeFilmePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_CBXNomeFilmePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (CBXNomeFilme.isVisible()) {
            CCodFilm.setText(String.valueOf(modelFilme.getIdFilme()));
        }
    }//GEN-LAST:event_CBXNomeFilmePopupMenuWillBecomeInvisible

    private void CCodFilmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CCodFilmFocusLost
        // TODO add your handling code here:
        modelFilme = controllerFilme.getFilmeController(Integer.parseInt(CCodFilm.getText()));
        CBXNomeFilme.setSelectedItem(modelFilme.getFilTitulo());
    }//GEN-LAST:event_CCodFilmFocusLost

    private void ButAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAdicionarActionPerformed
        // TODO add your handling code here:
        modelFilme = controllerFilme.getFilmeController(Integer.parseInt(CCodFilm.getText()));
        DefaultTableModel modelo = (DefaultTableModel) tbl_cadastro.getModel();
        int cont = 0;
        for (int i = 0; i < cont; i++) {
            modelo.setNumRows(0);
        }
        modelo.addRow(new Object[]{
        modelFilme.getIdFilme(),
            modelFilme.getFilTitulo(),
            modelFilme.getFilValorReserva()
        });
    }//GEN-LAST:event_ButAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewReserva().setVisible(true);
        });
    }

    

    private void listarClientes() {
        listaModelClientes = controllerCliente.getListaClienteController();
        CBXNomeCliente.removeAllItems();
        for (int i = 0; i < listaModelClientes.size(); i++) {
            CBXNomeCliente.addItem(listaModelClientes.get(i).getCliNome());
        }
    }

    private void listarProdutos() {
        listaModelFilme = controllerFilme.getListaFilmeController();
        CBXNomeFilme.removeAllItems();
        for (int i = 0; i < listaModelFilme.size(); i++) {
            CBXNomeFilme.addItem(listaModelFilme.get(i).getFilTitulo());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAdicionar;
    private javax.swing.JButton ButCancelar1;
    private javax.swing.JButton ButNovo1;
    private javax.swing.JButton ButPesquisaConsulta;
    private javax.swing.JButton ButSalvar1;
    private componentes.UJComboBox CBXNomeCliente;
    private componentes.UJComboBox CBXNomeFilme;
    private javax.swing.JTextField CCodCliente;
    private javax.swing.JTextField CCodFilm;
    private javax.swing.JTextField CNumVenda;
    private javax.swing.JTextField CPesquisaConsulta;
    private javax.swing.JLabel LCodCliente;
    private javax.swing.JLabel LCodProd;
    private javax.swing.JLabel LNomeCliente;
    private javax.swing.JLabel LNumVenda;
    private javax.swing.JLabel LPesquisaConsulta;
    private javax.swing.JTabbedPane Paineis;
    private javax.swing.JPanel PainelCadastro;
    private javax.swing.JPanel PainelConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbl_cadastro;
    private javax.swing.JTable tbl_consulta;
    // End of variables declaration//GEN-END:variables
}
